CREATE USER regular_user;
GRANT CONNECT ON DATABASE mydb TO regular_user;
GRANT USAGE ON SCHEMA public TO regular_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO regular_user;
