version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  webserver:
    image: my-golang-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=postgres
volumes:
  postgres_data: